### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#19]
- [x] bottom padding on scrollable note
- [x] increase line height
- [x] deletion of gist is too ~~easy~~ prominent

**Comment by jcblw** [comment]
just pushed a scroll past end 72ca2268e37ca9fcb753559cb966bf3f34295ac7 to the editor, fixes first item.

**Comment by itsjustmath** [comment]
top padding in the editor causes a odd cut-off near the top

![save-settings-svg_md](https://cloud.githubusercontent.com/assets/635044/7830153/8bfe4920-03fe-11e5-83c6-cc13f5f85b8e.png)
