### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#21]
- [x] markdown-related shortcuts
- [x] new gist
- [x] save gist

**Comment by jcblw** [comment]
new gist and save gist are already implemented, can you please list what markdown-related shortcuts are.

**Comment by itsjustmath** [comment]
`CMD-B` - Bold the selected text
`CMD-I` -   Italicize the selected text
`CMD-~` - Strikethrough the selected text
`CMD-K` - Add a link, if theres a link in the clipboard already ,apply it to the selected text
`CMD-1` - Convert the selected text a h1 heading (ideally it would follow this same logic all the way to h6)
`CMD-U` - Convert the selected text to unordered list
`CMD-Option-U` - Convert the selected text to ordered list
`CMD-Shift-M`    - Convert the selected text to todo list `- [ ] example`
`CMD-M` - Mark todo item as done

It would be ideal if all of these shortcuts toggled their respective actions (eg. bold and unbold, )

`CMD+]` - indent
`CMD+[` - outdent

**Comment by jcblw** [comment]
just adding this like here for reference https://github.com/ajaxorg/ace/wiki/Embedding-API#adding-new-commands-and-keybindings

**Comment by itsjustmath** [comment]
Ace editor's [default keyboard shortcuts](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts)

**Comment by jcblw** [comment]
leaving the rest of the crazier shortcuts to v3
