### ISSUE TITLE
link to markdown shortcuts

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#23]
maybe [put it](https://help.github.com/articles/markdown-basics/) in the help menu

**Comment by jcblw** [comment]
link to shortcuts, or link to a what is markdown help?

**Comment by itsjustmath** [comment]
Do you have the ability to add those shortcuts to the menu bar? If so, I'd say just a link to explaining github flavored markdown

**Comment by jcblw** [comment]
yeah I can put them in the menu bar.
