### ISSUE TITLE
Menu styles broken

### ISSUE THREAD

**Issue by jcblw** [jcblw/pastila#32]
So with the latest merge some of the menu styles we kinda busted.

![screen shot 2015-06-07 at 10 08 35 am](https://cloud.githubusercontent.com/assets/578259/8025052/7b79b168-0cfd-11e5-86fc-88759eb36250.png)
![screen shot 2015-06-07 at 10 08 43 am](https://cloud.githubusercontent.com/assets/578259/8025053/7b7c85e6-0cfd-11e5-8a81-2b3e95175656.png)

**Comment by itsjustmath** [comment]
![create-note-modal](https://cloud.githubusercontent.com/assets/635044/8025461/bd5c4e1a-0d0c-11e5-9325-3919eacc37a4.png)

Yeah this modal got kinda busted too

**Comment by jcblw** [comment]
Im reopening this for the clipping issue.

**Comment by jcblw** [comment]
this is resolved now.
