### ISSUE TITLE
Highlighting not accurately showing the characters its highlighting

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#34]
![full_highlight_not_true_to_what_its_copying](https://cloud.githubusercontent.com/assets/635044/8042153/0eab3e8c-0dd2-11e5-87aa-20c1dc2fdb37.png)

Actually string that it copies:

> Although it’s a vector, you may want to keep the size of the SVG at the

**Comment by jcblw** [comment]
I think this is caused by the font-size being responsive.

**Comment by jcblw** [comment]
hmmm cant reproduce this. please open back up with replication steps if it occurs again.

**Comment by itsjustmath** [comment]
yeah i think it might be related to responsive text size, should we disable size change?
