### ISSUE TITLE
swaping out editor

### ISSUE THREAD

**Issue by jcblw** [jcblw/pastila#35]
ace is nice but seems to have alot more then we need for this project.

maybe we can check out something like this

http://codepen.io/kazzkiq/pen/xGXaKR

**Comment by itsjustmath** [comment]
does it have markdown syntax highlighting?

**Comment by jcblw** [comment]
yeah, http://prismjs.com/#languages-list I think it also gives us a ground level approach rather then something that is already super built out.

**Comment by itsjustmath** [comment]
Nice, super lightweight. I'm down.

**Comment by jcblw** [comment]
yeah working on coverting that micro editor into a react component should be pretty simple probably alot more performant as well.

**Comment by itsjustmath** [comment]
👌

**Comment by jcblw** [comment]
heres the progress, few bugs to smooth out. Its looking pretty good tho. https://github.com/jcblw/pastila/tree/feature/micro-editor

**Comment by itsjustmath** [comment]
I like it! Super sharp and clean.

**Comment by jcblw** [comment]
this might be too much work :/ it could be fun there is already a ton that should get worked on should not add more.
