### ISSUE TITLE
Precompilers css & es6

### ISSUE THREAD

**Issue by jcblw** [jcblw/pastila#38]
https://github.com/paulcbetts/electron-compile

this looks pretty awesome plus wee can get a precompiler for css in with this.

**Comment by itsjustmath** [comment]
oh fuck yeah

**Comment by jcblw** [comment]
gotta hold off on this, trying to implement this without breaking my initial hook for babel is causing an error. 

https://github.com/paulcbetts/electron-compile/issues/8

**Comment by jcblw** [comment]
I think Im going to go through and start converting this to React CSS styles.
