### ISSUE TITLE
checkboxes render incorrectly in markdown preview

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#52]
#### pastila

<img width="167" alt="jobs_md_preview_and_jobs_md" src="https://cloud.githubusercontent.com/assets/635044/11447677/2bf8e642-94ff-11e5-936f-22e6e79aa9a3.png">
#### github

<img width="151" alt="jobs_to_apply_for" src="https://cloud.githubusercontent.com/assets/635044/11447741/3915116a-9500-11e5-9c43-b19065f4e19a.png">

**Comment by jcblw** [comment]
hmm might have to switch over our markdown processor, I fer sher dont want to roll this myself.

**Comment by itsjustmath** [comment]
Don't worry about it then, not a big deal as the preview isn't really interactive. You can close the ticket if you want
