### ISSUE TITLE
Port to iOS & Android

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#55]
I know this would be _way_ far down the roadmap, and I'd love to help as my javascript skills progress - but this would be _effing_ awesome. I can't speak for the android app store, but there are no good gist/markdown apps for iPhone.

Some guy already made a [calculator app](https://github.com/benoitvallon/react-native-nw-react-calculator) in which the mobile, desktop and website apps all use the same code.

**Comment by jcblw** [comment]
The big issue it that the editor is web based, so unless we rewrote the editor this would not be possible.

**Comment by itsjustmath** [comment]
I'll close for now then. The idea just popped into my head and I wanted to jot it down.
