### ISSUE TITLE
Make links/URLs clickable

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#7]
![sprint-2_4_5_md](https://cloud.githubusercontent.com/assets/635044/7693024/db51dbd4-fd7f-11e4-9158-84a30cab81aa.png)

**Comment by jcblw** [comment]
on previews? or on this I wondering which one makes more sense.

**Comment by itsjustmath** [comment]
In pastila editor. Maybe `http://` stuff should be clickable unless its wrapped in `[mark](down.com)`

![screenshot_5_18_15__6_06_pm](https://cloud.githubusercontent.com/assets/635044/7693581/91127430-fd88-11e4-895c-19b40eb54cb8.png)

**Comment by itsjustmath** [comment]
Found an [issue (and possible solution)](https://github.com/ajaxorg/ace/issues/2453) in the ace editor repo ([demo](http://fs_previews.kumpf.cc/)). I like the idea of `CMD-click` on them in the editor, thus not having to select and copy then go in the browser

**Comment by itsjustmath** [comment]
Did some more research:
- ace/issues/: [Embedding a clickable link inside the editor](https://github.com/ajaxorg/ace/issues/1892)
- [demo](http://jsbin.com/jehopaja/4/edit?html,output)

**Comment by jcblw** [comment]
we do run into the issue of having to catch these links out and using eletron's api to open these link in a external window. With just that fix the link would still open in the electron window.

**Comment by jcblw** [comment]
http://electron.atom.io/docs/v0.31.0/api/shell/#shell-openexternal-url
