### ISSUE TITLE
Pasting rich formatted text (and special chars.?) causes layout and editability issues

### ISSUE THREAD

**Issue by itsjustmath** [jcblw/pastila#8]
![retina-ready_md](https://cloud.githubusercontent.com/assets/635044/7710786/f58dfb9a-fe1a-11e4-82cc-2d5b02aac041.png)

It seems that special characters cause the text to render weird and become uneditable

**Comment by itsjustmath** [comment]
most recently push completely broke copy/paste :disappointed:

**Comment by jcblw** [comment]
@itsjustmath I think that would belong in a new ticket.

**Comment by jcblw** [comment]
@itsjustmath can you give me a file with rich text that will cause this issue.

**Comment by itsjustmath** [comment]
looks like its not an issue anymore
